# Site settings
title: aXe-core, Accessibility engine for automated Web UI testing
description: > # this means to ignore newlines until "baseurl:"
  The Accessibility Engine for automated testing of HTML-based user
  interfaces. Drop the aXe on your accessibility defects!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://axe-core.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
  - node_modules
  - build

gems:
  - jekyll-redirect-from